SnomedRfsSql_ReleaseVersion_20191113

diff --git a/SnomedRfsMySql/bash/snomed_load_mysql b/SnomedRfsMySql/bash/snomed_load_mysql
--- a/SnomedRfsMySql/bash/snomed_load_mysql
+++ b/SnomedRfsMySql/bash/snomed_load_mysql
@@ -4,17 +4,71 @@
 # This script loads data from a release package into a MySql Database
 # Requires appropriate MySQL loader script to exist
 
+# FUNCTION DECLARATIONS FOR LATER USE
+function addLog()
+{
+	printf "`date +'%Y-%m-%d %T'` $1\n" >>"$log_file"
+}
+
+
+function buildTransitiveClosure {
+	if [[ "$snapcontent" == '' ]] ; then
+		printf "\nERROR: Cannot create Transitive Closure. Snapshot Release files not found!\n\n"
+		addLog "ERROR: Cannot create Transitive Closure. Snapshot Release files not found!"
+		exit
+	fi
+	if ! [ -f "$tc_source" ] ; then
+		printf "\nERROR: Cannot create Transitive Closure.\n\tRequired file not found: $tc_source\n\n"
+		addLog "ERROR: Cannot create Transitive Closure.\n\tRequired file not found: $tc_source"
+		exit
+	fi
+	printf "Starting transitive closure generator.\n\tSource: $tc_source\n\tTarget: $tc_target\n"
+	addLog "Starting transitive closure generator.\n\tSource: $tc_source\n\tTarget: $tc_target"
+	printf 	"\n-------------------------------------------------\n=  *****  PLEASE WAIT FOR A FEW MINUTES  *****\t=\n=  When transitive closure generation completes\t=\n=  you will be need to enter your DB password\t=\n-------------------------------------------------\n"
+	perl "$loaderFolder/lib/transitiveClosureRf2SnapMulti.pl" "$tc_source" "$tc_target"
+	printf "Transitive closure - output file is:\n\t$tc_target\n"
+	addLog "Transitive closure - output file is:\n\t$tc_target"
+}
+
+function setCfgValue()
+	{
+	local cfgName="$1"
+	local cfgValue="$2"
+	if ! [ -f "$user_prefs" ] ; then
+		echo "${cfgName}=${cfgValue}" >"$user_prefs"
+	else
+		sed '/'$cfgName'=/d' "$user_prefs" >"$tmp_prefs"
+		echo "${cfgName}=${cfgValue}" >>"$tmp_prefs"
+		mv -f "$tmp_prefs" "$user_prefs"
+	fi
+	}
+function getCfgValue()
+	{
+	local cfgName="$1"
+	local defaultValue="$2" #set default value
+	if ! [ -f "$user_prefs" ] ; then
+		echo "" "$user_prefs"
+	fi
+	cfgValue=`sed '/^[^=]*$/d;s/'$cfgName'=\(.*\)/\1/;/.*=.*/d' "$user_prefs"`
+	if [[ $cfgValue == '' ]] ; then
+		cfgValue="$defaultValue"
+	fi
+	}
+
+# END OF FUNCTION DECLARATIONS
+
 self=$0
 prog=`basename "$self"`
 mysqlrun='mysql'
 mysqlload='mysql_load'
 mode="standard"
 cnfname="my_snomedimport_client"
+notc=''
 
-# By default uses the VP_latest script 
-# (VP=Variable Path ... to the script can modify the Release file path and 'latest' is literally the last one generated)
+# By default uses the create_latest.sql script 
+# (Based on the Variable Path version substitution made later in the script)
 loadkey=''
-loadkey_default='VP_latest'
+loadkey_default='create_latest'
 
 Q='"'
 
@@ -106,7 +160,7 @@ done
 
 # If loaderFolder not set by command line set it here 
 # Other scripts are relative to the defined base folder
-if [ "$loaderFolder" == "" ] ; then
+if [[ "$loaderFolder" == "" ]] ; then
 	# First check folder containing the script
 	loaderFolder=`dirname "$self"`
 	cd $loaderFolder
@@ -128,49 +182,45 @@ if [ "$loaderFolder" == "" ] ; then
 	fi
 fi
 
-
 cd "$loaderFolder"
-
+echo "$loaderFolder"
 cnf_file="${loaderFolder}/cnf/${cnfname}.cnf"
 log_file="${loaderFolder}/cnf/${USER}_load_log.txt"
 user_prefs="${loaderFolder}/cnf/${USER}_prefs.txt"
 tmp_prefs="${loaderFolder}/cnf/${USER}_tmp.txt"
-
-function addLog()
-{
-	printf "`date +'%Y-%m-%d %T'` $1\n" >>"$log_file"
-}
 printf ''> "$log_file"
 addLog "Started snomed_load_mysql"
+
+# If SQL loader script identifying tag not set prompt for this
+loaderTags=`ls -1 "$loaderFolder/mysql_load"|grep '^sct_mysql_load_\(create\|extend\|update\)_.*\.sql$'|sed 's/^sct_mysql_load_/ /;s/\.sql$//'`
+if [[ $loaderTags == '' ]] ; then
+	printf 'ERROR! No loader SQL scripts found.\n\n'
+	exit
+elif [[ $loaderTags == 'create_latest' ]] ; then
+	loadkey=$loaderTags
+elif [[ $loadkey == '' ]] ; then
+	printf "Loader script identifying tag defaults to 'create_latest' if left blank.\nAlternatively you can specify another scripts.\n\tEach script has a 'create_' or 'update_' prefix which indicates if it:\n - creates a new database; or\n - updates the views and stored procedures in an existing database.\nAvailable scripts are listed below:\n$loaderTags\n\n"
+	read -p "Loader script identifying tag: " loadkey
+fi
+if [[ $loadkey == '' ]] ; then
+	loadkey=$loadkey_default
+elif ! [[ $loadkey =~ ^[ceu].*[ed]_.* ]] ; then
+	printf 'ERROR! Invalid loadkey specified.\n\tLoadkey must start with "create_" "extend_" or "update_"\n\n'
+	exit
+fi
+
+sql_file="${loaderFolder}/$mysqlload/sct_mysql_load_${loadkey}.sql"
+
+if [ -f "$sql_file" ] ; then
+	printf "\nLOADER SCRIPT: ${loadkey}\n\n"
+else
+	printf "\nERROR! Loader script not found: ${loadkey}\n\n"
+	addLog "ERROR! Loader script not found: ${loadkey}"
+fi
 
 if ! [ -f "$user_prefs" ] ; then
 	echo "" >"$user_prefs"
 fi
-
-function setCfgValue()
-	{
-	local cfgName="$1"
-	local cfgValue="$2"
-	if ! [ -f "$user_prefs" ] ; then
-		echo "${cfgName}=${cfgValue}" >"$user_prefs"
-	else
-		sed '/'$cfgName'=/d' "$user_prefs" >"$tmp_prefs"
-		echo "${cfgName}=${cfgValue}" >>"$tmp_prefs"
-		mv -f "$tmp_prefs" "$user_prefs"
-	fi
-	}
-function getCfgValue()
-	{
-	local cfgName="$1"
-	local defaultValue="$2" #set default value
-	if ! [ -f "$user_prefs" ] ; then
-		echo "" "$user_prefs"
-	fi
-	cfgValue=`sed '/^[^=]*$/d;s/'$cfgName'=\(.*\)/\1/;/.*=.*/d' "$user_prefs"`
-	if [[ $cfgValue == '' ]] ; then
-		cfgValue="$defaultValue"
-	fi
-	}
 
 if ! [ -f "$user_prefs" ] ; then
 	echo "" > "$user_prefs"
@@ -188,7 +238,7 @@ prevUser=$cfgValue
 addLog "User Defaults for:$USER\n\tReleasePath:$releasePath\n\tPrevRelease:$prevRelease\n\tPrevUser:$prevUser"
 
 
-if [[ releasePath == "" ]] ; then
+if [[ "$releasePath" != "" ]] ; then
 	if ! [ -d $releasePath ] ; then
 		releasePath=""
 	fi
@@ -204,100 +254,113 @@ fi
 
 # BEFORE SET
 
-if [[ "$thisRelease" == "" ]] ; then
-	if [[ "$releasePath" == "" ]] ; then
-		printf "Enter the full path to the release folder or zip archive.\n"
-	elif [[ "$prevRelease" != '' ]] ; then
-		printf "Enter one of the following:\n - Full path to release folder or zip archive\n - Name of release folder or zip archive in:\n\t${releasePath}\n - Blank for previously loaded release:\n\t(${Q}${prevRelease}${Q})\n"
+if [[ $loadkey =~ ^update ]] ; then
+	thisRelease='No_Folder_Required'
+else
+	if [[ "$thisRelease" == ""  && $loadkey =~ ^[ce] ]] ; then
+		if [[ "$releasePath" == "" ]] ; then
+			printf "Enter the full path to the release folder or zip archive.\n"
+		elif [[ "$prevRelease" != '' ]] ; then
+			printf "Enter one of the following:\n - Full path to release folder or zip archive\n - Name of release folder or zip archive in:\n\t${releasePath}\n - Blank for previously loaded release:\n\t(${Q}${prevRelease}${Q})\n"
+		else
+			printf "Enter one of the following:\n - Full path to release folder or zip archive\n - Name of release folder or zip archive in:\n\t$releasePath\n"
+		fi
+		read -p "Release folder path: " thisRelease
+		if [[ "$thisRelease" == '' ]] ; then
+			thisRelease="$prevRelease"
+		fi
+	fi
+
+	# FIX REFERENCES TO $HOME IN THE PATH
+	if [[ $thisRelease =~ ^\$HOME ]] ; then
+		thisRelease="$HOME${thisRelease:5}"
+		echo $thisRelease
+	fi
+
+	# If $thisRelease does not start at root "/" then prepend with $releasePath
+
+	if ! [[ $thisRelease =~ ^/ ]] ; then
+		thisRelease="$releasePath/$thisRelease"
+	fi
+
+	# If zip file named ignore the .zip extension in folder name
+	# In all cases set and test the matching .zip file
+
+	if [[ $thisRelease =~ \.zip$ ]] ; then
+		releaseZip="$thisRelease"
+		thisRelease="${thisRelease%.zip}"
 	else
-		printf "Enter one of the following:\n - Full path to release folder or zip archive\n - Name of release folder or zip archive in:\n\t$releasePath\n"
+		releaseZip="${thisRelease}.zip"
 	fi
-	read -p "Release folder path: " thisRelease
-	if [[ "$thisRelease" == '' ]] ; then
-		thisRelease="$prevRelease"
+
+	if [ -d "$thisRelease" ] ; then
+		# Folder found so use this
+		printf "\nRELEASE FOLDER: $thisRelease\n"
+		addLog "Release folder found: $thisRelease"
+		thisRelease="$thisRelease"
+	elif [ -f "$releaseZip" ] ; then
+		# No folder but zipfile found so unzip
+		printf "\nRELEASE ZIP ARCHIVE: $releaseZip\n"
+		addLog "Release Zip file found: $thisRelease"
+		unzipFolder=`dirname "$thisRelease"`
+		unzip "$releaseZip" -q -d $unzipFolder
+		printf "\nRELEASE FOLDER: $thisRelease\n"
+	else
+		# No folder or zipfile found so exit here
+		printf "ERROR! Release folder not found: $thisRelease\n\n"
+		addLog "ERROR! Release folder not found: $thisRelease"
+		exit
 	fi
-fi
 
-printf "RELEASE FOLDER: $thisRelease\n"
-# FIX REFERENCES TO $HOME IN THE PATH
-if [[ $thisRelease =~ ^\$HOME ]] ; then
-	thisRelease="$HOME${thisRelease:5}"
-	echo $thisRelease
-fi
-
-# If $thisRelease does not start at root "/" then prepend with $releasePath
-
-if ! [[ $thisRelease =~ ^/ ]] ; then
-	thisRelease="$releasePath/$thisRelease"
-fi
-
-# If zip file named ignore the .zip extension in folder name
-# In all cases set and test the matching .zip file
-
-if [[ $thisRelease =~ \.zip$ ]] ; then
-	releaseZip="$thisRelease"
-	thisRelease="${thisRelease%.zip}"
-else
-	releaseZip="${thisRelease}.zip"
-fi
-
-if [ -d "$thisRelease" ] ; then
-	# Folder found so use this
-	printf "Release folder found: $thisRelease\n"
-	addLog "Release folder found: $thisRelease"
-	thisRelease="$thisRelease"
-elif [ -f "$releaseZip" ] ; then
-	# No folder but zipfile found so unzip
-	printf "Release Zip file found: $thisRelease\n"
-	addLog "Release Zip file found: $thisRelease"
-	unzipFolder=`dirname "$thisRelease"`
-	unzip "$releaseZip" -q -d $unzipFolder
-else
-	# No folder or zipfile found so exit here
-	printf "ERROR! Release folder not found: $thisRelease\n\n"
-	addLog "ERROR! Release folder not found: $thisRelease"
-	exit
-fi
-
-if ! [ -d "$thisRelease/Full" ] ; then
-	printf "ERROR! Release folder: $thisRelease does not contain a Full subfolder\n\n"
-	addLog "ERROR! Release folder: $thisRelease does not contain a Full subfolder"
-	exit
-elif ! [ -d "$thisRelease/Snapshot" ] ; then
-	printf "ERROR! Release folder: $thisRelease does not contain a Snapshot subfolder\n\n"
-	addLog "ERROR! Release folder: $thisRelease does not contain a Snapshot subfolder"
-	exit
-else
-	setCfgValue 'relpath' `dirname "$thisRelease"`
-	setCfgValue 'prevrel' `basename "$thisRelease"`	
+	if ! [ -d "$thisRelease/Full" ] ; then
+		printf "ERROR! Release folder: $thisRelease does not contain a Full subfolder\n\n"
+		addLog "ERROR! Release folder: $thisRelease does not contain a Full subfolder"
+		exit
+	elif ! [ -d "$thisRelease/Snapshot" ] ; then
+		printf "ERROR! Release folder: $thisRelease does not contain a Snapshot subfolder\n\n"
+		addLog "ERROR! Release folder: $thisRelease does not contain a Snapshot subfolder"
+		exit
+	else
+		setCfgValue 'relpath' `dirname "$thisRelease"`
+		setCfgValue 'prevrel' `basename "$thisRelease"`	
+	fi
+	if ! [ -d "$thisRelease" ] ; then
+		printf "Release folder not found!\n Path: $thisRelease\n"
+		addLog "Release folder not found!\n\tPath: $thisRelease"
+		exit
+	fi
+	if ! [ -d "$thisRelease/Full" ] ; then 
+		printf "Release folder does not contain a Full release subfolder!\n Path: $thisRelease/Full\n"
+		addLog "Release folder does not contain a Full release subfolder!\n\tPath: $thisRelease/Full"
+		exit
+	fi
+	echo "$thisRelease" >cnf/lastrelpath.txt
+	snapcontent="$thisRelease/Snapshot/Terminology"
+	tc_source=''
+	if [ -d "$snapcontent" ] ; then
+		prevpath=$PWD
+		cd "$snapcontent"
+		tc_sourcefile=`echo *sct2_Relationship_Snapshot_*.txt|head -n 1`
+		if [[ $tc_sourcefile =~ [0-9]{8}.txt$ ]] ; then
+			tc_version=${tc_sourcefile/#*Snapshot/}
+			tc_target="$thisRelease/xder_transitiveClosure_Snapshot${tc_version}"
+			tc_source="$snapcontent/$tc_sourcefile"
+		fi
+		cd "$prevpath"
+	else
+		snapcontent=''
+	fi
 fi
 
 # Get Database Name
 if [[ $dbname == '' ]] ; then
+	echo
 	read -p "Database name (default: snomedct): " dbname
 	if [[ "$dbname" == '' ]] ; then
 		dbname='snomedct'
 	fi
 fi
 addLog "Database name:$dbname"
-
-# If SQL loader script identifying tag not set prompt for this
-loaderTags=`ls -1 "$loaderFolder/mysql_load"|grep '^sct_mysql_load_[A-Z]\{2\}_.\{0,100\}\.sql$'|sed 's/^sct_mysql_load_//;s/\.sql$//'`
-echo $loaderTags
-if [[ $loaderTags == '' ]] ; then
-	printf 'ERROR! No loader SQL scripts found.\n\n'
-	exit
-elif [[ $loaderTags == 'VP_latest' ]] ; then
-	loadkey=$loaderTags
-elif [[ $loadkey == '' ]] ; then
-	printf "Loader script identifying tag defaults to 'VP_latest' if left blank.\nAlternatively you can specify one of the following scripts:\n$loaderTags\n"
-	read -p "Loader script identifying tag: " loadkey
-fi
-if [[ $loadkey == '' ]] ; then
-	loadkey=$loadkey_default
-fi
-
-sql_file="${loaderFolder}/$mysqlload/sct_mysql_load_${loadkey}.sql"
 
 # Get MySQL User Name
 getCfgValue 'mysqluser'
@@ -311,102 +374,57 @@ if [[ $mysqluser == '' ]] ; then
 fi
 addLog "MySQL username:$mysqluser"
 
-snapcontent="$thisRelease/Snapshot/Terminology"
-tc_source=''
-if [ -d "$snapcontent" ] ; then
-	prevpath=$PWD
-	cd "$snapcontent"
-	tc_sourcefile=`echo *sct2_Relationship_Snapshot_*.txt|head -n 1`
-	if [[ $tc_sourcefile =~ [0-9]{8}.txt$ ]] ; then
-		tc_version=${tc_sourcefile/#*Snapshot/}
-		tc_target="$thisRelease/xder_transitiveClosure_Snapshot${tc_version}"
-		tc_source="$snapcontent/$tc_sourcefile"
-	fi
-	cd "$prevpath"
-else
-	snapcontent=''
+if [[ "$mode" != "standard" ]] ; then
+	printf "MODE: $mode\n"
 fi
 
-function buildTransitiveClosure {
-	if [[ "$snapcontent" == '' ]] ; then
-		printf "\nERROR: Cannot create Transitive Closure. Snapshot Release files not found!\n\n"
-		addLog "ERROR: Cannot create Transitive Closure. Snapshot Release files not found!"
-		exit
+
+if [[ $loadkey =~ ^create ]] ; then
+	printf "\nTRANSITIVE CLOSURE: "
+	if [ -f "$tc_target" ] ; then
+		if [[ $mode =~ (forcetc) ]] ; then
+			buildTransitiveClosure
+		elif [[ $mode =~ (notc) ]] ; then
+			rm "$tc_target"
+			printf 'Removed previously built transitive closure file.\n'
+			addLog "Removed previously built transitive closure file"
+		else
+			printf 'Using previously built transitive closure file.\n'
+			addLog "Using previously built transitive closure file"
+		fi
+	elif [[ $mode =~ (notc|skiptc) ]] ; then
+		printf 'Skipping Transitive Closure Build\n'
+		addLog "Skipping Transitive Closure Build"
+	else
+		buildTransitiveClosure
 	fi
-	if ! [ -f "$tc_source" ] ; then
-		printf "\nERROR: Cannot create Transitive Closure.\n\tRequired file not found: $tc_source\n\n"
-		addLog "ERROR: Cannot create Transitive Closure.\n\tRequired file not found: $tc_source"
-		exit
-	fi
-	printf "Starting transitive closure generator.\n\tSource: $tc_source\n\tTarget: $tc_target\n"
-	addLog "Starting transitive closure generator.\n\tSource: $tc_source\n\tTarget: $tc_target"
-	printf 	"\n-------------------------------------------------\n=  *****  PLEASE WAIT FOR A FEW MINUTES  *****\t=\n=  When transitive closure generation completes\t=\n=  you will be need to enter your DB password\t=\n-------------------------------------------------\n"
-	perl "$loaderFolder/lib/transitiveClosureRf2SnapMulti.pl" "$tc_source" "$tc_target"
-	printf "Transitive closure - output file is:\n\t$tc_target\n"
-	addLog "Transitive closure - output file is:\n\t$tc_target"
-}
+fi
+
+if [ -f $tc_target ] ; then
+	notc=''
+else
+	notc='-- NO TC'
+fi
+
 
 sql_tmp="${loaderFolder}/$mysqlload/sct_mysql_temp.sql"
 
-printf "\n------------------------\nConfig file: $cnf_file\nPort: $portnumber\nSQL file: $sqlfile\nRelease Folder Path: $thisRelease\nDatabase name: $dbname\nMode: $mode\nREUSABLE COMMAND LINE:\n$prog -c $cnfname -p $portnumber -s $loadkey -r ""$thisRelease"" -d ""$dbname"" -u ""$mysqluser"" -mode $mode\n------------------------\n"
-
-if ! [ -d "$thisRelease" ] ; then
-	printf "Release folder not found!\n Path: $thisRelease\n"
-	addLog "Release folder not found!\n\tPath: $thisRelease"
-	exit
-fi
-if ! [ -d "$thisRelease/Full" ] ; then 
-	printf "Release folder does not contain a Full release subfolder!\n Path: $thisRelease/Full\n"
-	addLog "Release folder does not contain a Full release subfolder!\n\tPath: $thisRelease/Full"
-	exit
-fi
-echo "$thisRelease" >cnf/lastrelpath.txt
-
-if [ -f "$tc_target" ] ; then
-	if [[ $mode =~ (forcetc) ]] ; then
-		buildTransitiveClosure
-	elif [[ $mode =~ (notc) ]] ; then
-		rm "$tc_target"
-		printf 'Removed previously built transitive closure file.\n'
-		addLog "Removed previously built transitive closure file"
-	else
-		printf 'Using previously built transitive closure file.\n'
-		addLog "Using previously built transitive closure file"
-	fi
-elif [[ $mode =~ (notc|skiptc) ]] ; then
-	echo "Skipping Transitive Closure Build"
-	addLog "Skipping Transitive Closure Build"
-else
-	buildTransitiveClosure
-fi
-
-# Depending on whether Transitive Closure File is found
-# Lines '-- ifTC' and '-- fiTC' lines will be replaced either with blank line or start and end block comments
-# This ensure the final script will not attempt to access transitive closure if it is not present
-if [ -f "$tc_target" ] ; then
-	ifTC=''
-	fiTC=''
-else
-	ifTC='/*'
-	fiTC='*/'
-fi
+printf "\n------------------------\nSETTINGS\n\nSQL file: $sql_file\nRelease Folder Path: $thisRelease\nDatabase name: $dbname\n\nConfig file: $cnf_file\nPort: $portnumber\nMode: $mode\n\nREUSABLE COMMAND LINE:\n$prog -c $cnfname -p $portnumber -s $loadkey -r ""$thisRelease"" -d ""$dbname"" -u ""$mysqluser"" -mode $mode\n\n------------------------\n"
 
 thisReldate=`sed 's/^.*_\(20[0-9]\{6\}\).*$/\1/' <<<"$thisRelease"`
 
 if [[ $mode =~ (reuse) ]] ; then
 	printf "Debug skipping Script Regeneration - Will reuse current temp file\n"
 else
-	sed 's#$HOME/#'"${HOME}/"'#g;s#$RELPATH/#'"${thisRelease}/"'#g;s#$RELDATE#'"${thisReldate}"'#g;s#$DBNAME#'"${dbname}"'#g;s#^-- ifTC#'"${ifTC}"'#;s#^-- fiTC#'"${fiTC}"'#g' "$sql_file" >"$sql_tmp"
+	sed 's#$HOME/#'"${HOME}/"'#g;s#$RELPATH/#'"${thisRelease}/"'#g;s#$RELDATE#'"${thisReldate}"'#g;s#$DBNAME#'"${dbname}"'#g;s#$NOTC#'${notc}'#g' "$sql_file" >"$sql_tmp"
 fi
 
-# Keep line below commented out except for testing without running database import
+# NO LOAD DEBUG EXIT OPTION
 if [[ $mode =~ noload ]] ; then
  echo "DEBUG EXIT"
  exit
 fi
 #
-
-
 
 printf 	"\n-------------------------------------------------\n=  **  PLEASE ENTER YOUR MYSQL PASSWORD  **\t=\n= You can then leave the database build to run.\t=\n= A step by step progress report will be shown\t=\n= but there is no need for further user input.\t=\n-------------------------------------------------\n"
 
@@ -415,9 +433,9 @@ if ! [[ "$PATH" =~ mysql/bin ]] ; then
    PATH=${PATH}:/usr/local/mysql/bin
 fi
 
-# mysql --defaults-extra-file="${cnf_file}"  --protocol=tcp --host=localhost --port=${portnumber} --default-character-set=utf8mb4  --comments --user $mysqluser --password  < "${sql_tmp}"
+# mysql --defaults-extra-file="${cnf_file}"  --protocol=tcp --host=localhost --port=${portnumber} --default-character-set=utf8mb4 --user $mysqluser --password  < "${sql_tmp}"
 
-${mysqlrun} --defaults-extra-file="${cnf_file}"  --protocol=tcp --host=localhost --port=${portnumber} --default-character-set=utf8mb4 --comments --user $mysqluser --password  < "${sql_tmp}"
+${mysqlrun} --defaults-extra-file="${cnf_file}"  --protocol=tcp --host=localhost --port=${portnumber} --default-character-set=utf8mb4 --user $mysqluser --password  < "${sql_tmp}"
 err=$?
 
 if [[ $err != 0 ]] ; then
